// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0TXPFaxv-7wkDJibLdNuKQF1Gv4XnfbI',
    appId: '1:1076749618274:web:e1233435f4f6dd2834553b',
    messagingSenderId: '1076749618274',
    projectId: 'dream-destiny-86e73',
    authDomain: 'dream-destiny-86e73.firebaseapp.com',
    storageBucket: 'dream-destiny-86e73.appspot.com',
    measurementId: 'G-SYXYRN74SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW2cbrintyRTAX70y63u-9mksumhu3zII',
    appId: '1:1076749618274:android:457d273a38f3582134553b',
    messagingSenderId: '1076749618274',
    projectId: 'dream-destiny-86e73',
    storageBucket: 'dream-destiny-86e73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8t-jL1gA5XCdmjY56kFF5LjCkCWf5L3Q',
    appId: '1:1076749618274:ios:fe77c7d3ff4fd6ac34553b',
    messagingSenderId: '1076749618274',
    projectId: 'dream-destiny-86e73',
    storageBucket: 'dream-destiny-86e73.appspot.com',
    iosBundleId: 'com.example.dreamDestiny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8t-jL1gA5XCdmjY56kFF5LjCkCWf5L3Q',
    appId: '1:1076749618274:ios:fe77c7d3ff4fd6ac34553b',
    messagingSenderId: '1076749618274',
    projectId: 'dream-destiny-86e73',
    storageBucket: 'dream-destiny-86e73.appspot.com',
    iosBundleId: 'com.example.dreamDestiny',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0TXPFaxv-7wkDJibLdNuKQF1Gv4XnfbI',
    appId: '1:1076749618274:web:c980cc662d38627d34553b',
    messagingSenderId: '1076749618274',
    projectId: 'dream-destiny-86e73',
    authDomain: 'dream-destiny-86e73.firebaseapp.com',
    storageBucket: 'dream-destiny-86e73.appspot.com',
    measurementId: 'G-7S2NTX6FM6',
  );
}
